services:
  postgres:
    image: bitnami/postgresql@sha256:c30c796dcf96a67a405b905bf6aaf8d6c957d5c2fe729db6e67e2760e21fd9f8
    container_name: unifor-books-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRESQL_USERNAME: biblioteca
      POSTGRESQL_PASSWORD: biblioteca123
      POSTGRESQL_DATABASE: unifor_books
    volumes:
      - postgres_data:/bitnami/postgresql

volumes:
  postgres_data: